"""Levels 16-20 (added to designs.LEVELS)."""
from designs import L, node, tr, gate, LEVELS

# ---------------------------------------------------------------- 16: Pass + AND
lv = L()
node(lv, 'S', 4, 0, 'F', 'start')
node(lv, 'HG', 0, 0, 'F', 'holder', pass_='Green')
node(lv, 'LG', 0, 4, 'F', 'lock', pass_='Green')
node(lv, 'HR', 0, 8, 'F', 'holder', pass_='Red')
node(lv, 'LR', 4, 8, 'F', 'lock', pass_='Red')
node(lv, 'V1', 8, 8, 'V', 'via')
node(lv, 'LG2', 8, 0, 'F', 'lock', pass_='Green')
node(lv, 'A1', 8, 4, 'F', 'and')
node(lv, 'A2', 4, 8, 'B', 'and')
node(lv, 'G', 4, 4, 'B', 'goal')
tr(lv, 'S', 'HG', 'F'); tr(lv, 'HG', 'LG', 'F'); tr(lv, 'LG', 'HR', 'F'); tr(lv, 'HR', 'LR', 'F'); tr(lv, 'LR', 'V1', 'F')
tr(lv, 'S', 'LG2', 'F'); tr(lv, 'LG2', 'A1', 'F')
tr(lv, 'V1', 'A2', 'B'); tr(lv, 'A2', 'G', 'B', gate=gate('and', ['A1', 'A2']))
LEVELS[16] = lv

# ---------------------------------------------------------------- 17: Pass + Data + AND
lv = L()
node(lv, 'S', 0, 0, 'F', 'start')
node(lv, 'HR', 4, 0, 'F', 'holder', pass_='Red')
node(lv, 'A1', 8, 0, 'F', 'and')
node(lv, 'LG', 4, 4, 'F', 'lock', pass_='Green')
node(lv, 'D1', 4, 8, 'F', data=True)
node(lv, 'V0', 0, 4, 'V', 'via')
node(lv, 'V1', 8, 4, 'V', 'via')
node(lv, 'HG', 0, 8, 'B', 'holder', pass_='Green')
node(lv, 'LR', 4, 4, 'B', 'lock', pass_='Red')
node(lv, 'D2', 4, 0, 'B', data=True)
node(lv, 'A2', 8, 8, 'B', 'and')
node(lv, 'G', 8, 0, 'B', 'goal')
tr(lv, 'S', 'HR', 'F'); tr(lv, 'HR', 'A1', 'F'); tr(lv, 'HR', 'LG', 'F'); tr(lv, 'LG', 'D1', 'F'); tr(lv, 'LG', 'V1', 'F'); tr(lv, 'S', 'V0', 'F')
tr(lv, 'V0', 'HG', 'B'); tr(lv, 'V0', 'LR', 'B'); tr(lv, 'LR', 'D2', 'B'); tr(lv, 'LR', 'V1', 'B'); tr(lv, 'V1', 'A2', 'B')
tr(lv, 'V1', 'G', 'B', gate=gate('and', ['A1', 'A2']))
LEVELS[17] = lv

# ---------------------------------------------------------------- 18: All
lv = L()
node(lv, 'S', 0, 0, 'F', 'start')
node(lv, 'N1', 4, 0, 'F', 'sw')
node(lv, 'C1', 8, 0, 'F')
node(lv, 'D1', 8, 4, 'F', data=True)
node(lv, 'HR', 4, 4, 'F', 'holder', pass_='Red')
node(lv, 'V1', 4, 8, 'V', 'via')
node(lv, 'V2', 8, 8, 'V', 'via')
node(lv, 'LR', 0, 8, 'B', 'lock', pass_='Red')
node(lv, 'A1', 0, 4, 'B', 'and')
node(lv, 'D2', 0, 0, 'B', data=True)
node(lv, 'A2', 8, 4, 'B', 'and')
node(lv, 'G', 4, 4, 'B', 'goal')
tr(lv, 'S', 'N1', 'F')
tr(lv, 'N1', 'C1', 'F', gate=gate('normal', ['N1'], open_=True))
tr(lv, 'C1', 'D1', 'F'); tr(lv, 'D1', 'V2', 'F')
tr(lv, 'N1', 'HR', 'F', gate=gate('normal', ['N1'], open_=False))
tr(lv, 'HR', 'V1', 'F')
tr(lv, 'V1', 'LR', 'B'); tr(lv, 'LR', 'A1', 'B'); tr(lv, 'A1', 'D2', 'B')
tr(lv, 'V2', 'A2', 'B')
tr(lv, 'A1', 'G', 'B', gate=gate('and', ['A1', 'A2']))
tr(lv, 'A2', 'G', 'B', gate=gate('and', ['A1', 'A2']))
LEVELS[18] = lv

# ---------------------------------------------------------------- 19: All
lv = L()
node(lv, 'S', 0, 4, 'F', 'start')
node(lv, 'N1', 0, 8, 'F', 'sw')
node(lv, 'C1', 4, 4, 'F')
node(lv, 'HR', 4, 0, 'F', 'holder', pass_='Red')
node(lv, 'A1', 8, 4, 'F', 'and')
node(lv, 'V1', 8, 8, 'V', 'via')
node(lv, 'D1', 4, 8, 'F', data=True)
node(lv, 'LR', 4, 8, 'B', 'lock', pass_='Red')
node(lv, 'A2', 0, 8, 'B', 'and')
node(lv, 'D2', 0, 4, 'B', data=True)
node(lv, 'G', 8, 4, 'B', 'goal')
tr(lv, 'S', 'N1', 'F')
tr(lv, 'S', 'C1', 'F', gate=gate('normal', ['N1'], open_=False))
tr(lv, 'C1', 'HR', 'F'); tr(lv, 'C1', 'A1', 'F'); tr(lv, 'A1', 'V1', 'F')
tr(lv, 'N1', 'D1', 'F', gate=gate('and', ['A1', 'A2'], inverted=True))
tr(lv, 'V1', 'LR', 'B'); tr(lv, 'LR', 'A2', 'B'); tr(lv, 'A2', 'D2', 'B')
tr(lv, 'V1', 'G', 'B', gate=gate('and', ['A1', 'A2']))
LEVELS[19] = lv

# ---------------------------------------------------------------- 20: All
lv = L()
node(lv, 'S', 0, 0, 'F', 'start')
node(lv, 'HG', 4, 0, 'F', 'holder', pass_='Green')
node(lv, 'N1', 8, 0, 'F', 'sw')
node(lv, 'V1', 8, 4, 'V', 'via')
node(lv, 'LR', 4, 4, 'F', 'lock', pass_='Red')
node(lv, 'D1', 0, 4, 'F', data=True)
node(lv, 'N2', 0, 8, 'F', 'sw')
node(lv, 'V2', 4, 8, 'V', 'via')
node(lv, 'HR', 8, 8, 'B', 'holder', pass_='Red')
node(lv, 'LG', 4, 4, 'B', 'lock', pass_='Green')
node(lv, 'D2', 0, 4, 'B', data=True)
node(lv, 'A1', 4, 0, 'B', 'and')
node(lv, 'A2', 0, 8, 'B', 'and')
node(lv, 'D3', 4, 10, 'B', data=True)
node(lv, 'LR2', 0, 6, 'B', 'lock', pass_='Red')
node(lv, 'G', 0, 0, 'B', 'goal')
tr(lv, 'S', 'HG', 'F'); tr(lv, 'HG', 'N1', 'F'); tr(lv, 'S', 'D1', 'F')
tr(lv, 'N1', 'V1', 'F', gate=gate('normal', ['N2'], open_=False))
tr(lv, 'HG', 'LR', 'F'); tr(lv, 'LR', 'D1', 'F'); tr(lv, 'D1', 'N2', 'F')
tr(lv, 'LR', 'V2', 'F', gate=gate('normal', ['N1'], open_=False))
tr(lv, 'V1', 'HR', 'B'); tr(lv, 'V1', 'LG', 'B'); tr(lv, 'LG', 'D2', 'B'); tr(lv, 'LG', 'A1', 'B')
tr(lv, 'V2', 'A2', 'B'); tr(lv, 'V2', 'D3', 'B'); tr(lv, 'D2', 'LR2', 'B'); tr(lv, 'LR2', 'A2', 'B')
tr(lv, 'A1', 'G', 'B', gate=gate('and', ['A1', 'A2']))
tr(lv, 'D2', 'G', 'B', gate=gate('and', ['A1', 'A2']))
LEVELS[20] = lv
