"""
Exports the chosen generated hard levels (hard_<n>.json from gen.py) to Unity JSON + a solution sheet:
  python export_hard.py <Assets/PCB/LevelData> 21:<seed> 22:<seed> ...
Renames nodes to the usual ids (S, G, V, N, A, HR/HG, LR/LG, D, C, X = decoy never visited by the solution),
moves the content to the board corner and re-checks layout + solution.
"""
import json, os, sys
sys.path.insert(0, '.')
from pcbsolver import check_layout
from gen import analyse
from deadends import dead_states


def shrink(lv):
    N = lv['nodes']
    pts = [(d['x'], d['y']) for d in N.values()] + [tuple(p) for t in lv['traces'] for p in t['bends']]
    mx, my = min(p[0] for p in pts), min(p[1] for p in pts)
    for d in N.values():
        d['x'] -= mx; d['y'] -= my
    for t in lv['traces']:
        t['bends'] = [[p[0] - mx, p[1] - my] for p in t['bends']]
    pts = [(d['x'], d['y']) for d in N.values()] + [tuple(p) for t in lv['traces'] for p in t['bends']]
    lv['size'] = (max(p[0] for p in pts), max(p[1] for p in pts))


def rename(lv, sol):
    N = lv['nodes']
    visited = {s[6:] for s in sol if s.startswith('move->')}
    start = next(n for n, d in N.items() if d['type'] == 'start')
    visited.add(start)
    # number in reading order (top-left first) so ids are easy to find on the board
    order = sorted(N, key=lambda n: (-N[n]['y'], N[n]['x']))
    counters, new = {}, {}

    def nxt(prefix):
        counters[prefix] = counters.get(prefix, 0) + 1
        return f'{prefix}{counters[prefix]}'

    for n in order:
        d = N[n]
        t = d['type']
        if t == 'start': new[n] = 'S'
        elif t == 'goal': new[n] = 'G'
        elif t == 'via': new[n] = nxt('V') if n in visited else nxt('XV')
        elif t == 'sw': new[n] = nxt('N')
        elif t == 'and': new[n] = nxt('A')
        elif t == 'holder': new[n] = nxt('H' + d['pass'][0])
        elif t == 'lock': new[n] = nxt('L' + d['pass'][0])
        elif d['data']: new[n] = nxt('D')
        else: new[n] = nxt('C') if n in visited else nxt('X')
    lv['nodes'] = {new[n]: d for n, d in N.items()}
    for t in lv['traces']:
        t['a'], t['b'] = new[t['a']], new[t['b']]
        if t['gate']:
            t['gate']['switches'] = [new[s] for s in t['gate']['switches']]
    return lv


def pretty(sol):
    out = []
    for s in sol:
        if s.startswith('move->'): out.append('→ ' + s[6:])
        elif s == 'flip': out.append('**flip**')
        elif s.startswith('press'): out.append('**press ' + s[6:] + '**')
        elif s.startswith('take'): out.append('**take ' + s[5:] + '**')
    return ' '.join(out)


def main():
    out_dir = sys.argv[1]
    picks = [tuple(int(v) for v in a.split(':')) for a in sys.argv[2:]]
    levels, sheet = [], ['# Claude levels 21+ (hard) — solutions\n',
                         'Generated by `Tools/LevelDesign/gen.py` (layout → mechanics search → prune) and checked by the solver. '
                         '"Shortest" = fewest actions (moves + Space presses). "Forced" = the fewest pass takes / switch '
                         'presses ANY solution needs.\n',
                         'Node ids: S start, G goal, V via, N normal switch, A AND switch, HR/HG red/green pass holder, '
                         'LR/LG red/green pass lock, D data, C capacitor, X / XV decoy capacitor / via (never needed).\n']
    for number, seed in picks:
        res = next(r for r in json.load(open(f'hard_{number}.json')) if r['seed'] == seed)
        lv = res['level']
        shrink(lv)
        a = analyse(lv)
        lv = rename(lv, a['sol'])
        a = analyse(lv)
        errs = check_layout(lv, size=max(lv['size']))
        assert a and not errs, (number, errs)
        N = lv['nodes']
        nodes = [dict(id=n, type=d['type'], side=d['side'], x=d['x'], y=d['y'], data=bool(d.get('data')),
                      passColour=d.get('pass') or '', on=bool(d.get('on'))) for n, d in N.items()]
        traces = []
        for t in lv['traces']:
            g = t.get('gate') or {}
            traces.append(dict(a=t['a'], b=t['b'], side=t['side'], bends=[dict(x=p[0], y=p[1]) for p in t['bends']],
                               gate=g.get('kind', 'none'), gateOpen=bool(g.get('open', False)),
                               gateInverted=bool(g.get('inverted', False)), switches=g.get('switches', [])))
        W, H = lv['size']
        levels.append(dict(name=f'Claude lvl {number}', number=number, sizeX=W, sizeY=H, nodes=nodes, traces=traces))
        gates = [t for t in lv['traces'] if t['gate']]
        sheet.append(f'## Claude lvl {number}\n')
        sheet.append(f'Board {W}x{H}, {len(N)} nodes, {len(lv["traces"])} traces, {len(gates)} gates, '
                     f'{sum(1 for d in N.values() if d.get("data"))} data. Shortest solution: **{a["length"]} actions** '
                     f'({a["length"] - a["inter"]} moves, {a["takes"]} pass takes, {a["presses"]} presses, {a["flips"]} flips). '
                     f'Forced: ≥ {a["min_takes"]} pass takes, ≥ {a["min_press"]} presses. Reachable states: {a["states"]}.\n')
        for t in gates:
            g = t['gate']
            kind = 'AND gate' if g['kind'] == 'and' else ('gate, starts OPEN' if g.get('open') else 'gate, starts shut')
            sheet.append(f'- {t["a"]} – {t["b"]} ({t["side"]}): {kind}, switches {", ".join(g["switches"])}')
        sheet.append('')
        sheet.append(pretty(a['sol']) + '\n')
        total, dead, path = dead_states(lv)
        if dead:
            kinds = {}
            for st in sorted(dead, key=lambda st: len(path(st))):
                kinds.setdefault((st[0], st[1], st[4]), path(st))
            places = sorted({k[0] for k in kinds})
            sheet.append(f'**Stuck states:** {len(dead)} of {total} reachable states can no longer reach the goal '
                         f'(Restart needed). Trapped spots: {", ".join(places)}. Shortest way to get stuck:\n')
            sheet.append(pretty(min(kinds.values(), key=len)) + '\n')
        else:
            sheet.append('**Stuck states:** none - every mistake can be undone.\n')
        print(f'Claude lvl {number}: {W}x{H}, len {a["length"]}, takes>={a["min_takes"]}, presses>={a["min_press"]}')
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, 'claude_levels_hard.json'), 'w', encoding='utf-8') as f:
        json.dump(dict(levels=levels), f, indent=1)
    with open(os.path.join(out_dir, 'Claude_levels_hard_solutions.md'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(sheet))


if __name__ == '__main__':
    main()
