"""
Writes the solution sheet for the levels in the Level List (Assets/PCB/LevelList.asset), read straight from the
level prefabs:  python solutions.py <output.md>
For each level: shortest solution (fewest actions), the minimum pass takes / switch presses any solution needs,
and stuck states (reachable, but the goal can't be reached any more - Restart needed).
"""
import glob, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from prefab2level import parse
from gen import analyse
from deadends import dead_states

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')


def level_list():
    guid_to_path = {}
    for meta in glob.glob(os.path.join(ROOT, 'Assets/PCB/Levels/**/*.prefab.meta'), recursive=True):
        g = re.search(r'^guid: (\w+)', open(meta, encoding='utf-8').read(), re.M).group(1)
        guid_to_path[g] = meta[:-5]
    text = open(os.path.join(ROOT, 'Assets/PCB/LevelList.asset'), encoding='utf-8').read()
    main = int(re.search(r'mainStageCount: (\d+)', text).group(1))
    guids = re.findall(r'^  - \{fileID: -?\d+, guid: (\w+), type: 3\}', text.split('levels:')[1], re.M)
    return [guid_to_path[g] for g in guids], main


def pretty(sol):
    out = []
    for s in sol:
        if s.startswith('move->'): out.append('→ ' + s[6:])
        elif s == 'flip': out.append('**flip**')
        elif s.startswith('press'): out.append('**press ' + s[6:] + '**')
        elif s.startswith('take'): out.append('**take ' + s[5:] + '**')
    return ' '.join(out)


def main(out_path):
    paths, main_count = level_list()
    lines = ['# Inner Spark — level solutions\n',
             'Generated by `Tools/LevelDesign/solutions.py` from the level prefabs in the Level List (re-run it after '
             'editing a level). Node names are the GameObject names in each level. "Shortest" = fewest actions '
             '(moves + Space presses). "Forced" = the fewest pass takes / switch presses ANY solution needs. '
             '"Stuck" = states from which the goal can no longer be reached (only Restart helps).\n',
             '| # | Level | Board | Shortest | Forced takes / presses | Stuck states |', '|---|---|---|---|---|---|']
    details = []
    for i, path in enumerate(paths):
        name = re.search(r"levelName: '?(.*?)'?\n", open(path, encoding='utf-8').read()).group(1)
        tag = f'Bonus {i - main_count + 1}' if i >= main_count else str(i + 1)
        lv = parse(path)
        a = analyse(lv)
        if not a:
            lines.append(f'| {tag} | {name} | {lv["size"][0]}×{lv["size"][1]} | ❌ unsolvable | – | – |')
            details.append(f'## {tag}. {name}\n\n❌ The solver finds no solution.\n')
            continue
        total, dead, path_to = dead_states(lv)
        stuck = f'{len(dead)} of {total}' if dead else 'none'
        lines.append(f'| {tag} | {name} | {lv["size"][0]}×{lv["size"][1]} | {a["length"]} | {a["min_takes"]} / {a["min_press"]} | {stuck} |')
        d = [f'## {tag}. {name}\n',
             f'{a["length"]} actions: {a["length"] - a["inter"]} moves, {a["takes"]} pass takes, {a["presses"]} presses, '
             f'{a["flips"]} flips.\n', pretty(a['sol']) + '\n']
        if dead:
            kinds = {}
            for st in sorted(dead, key=lambda st: len(path_to(st))):
                kinds.setdefault((st[0], st[1], st[4]), path_to(st))
            spots = sorted({k[0] for k in kinds})
            d.append(f'**Stuck spots:** {", ".join(spots)}. Shortest way to get stuck: '
                     + pretty(min(kinds.values(), key=len)) + '\n')
        details.append('\n'.join(d))
        print(f'{tag:8} {name:28} shortest {a["length"]:3}  stuck {stuck}', flush=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n\n' + '\n'.join(details))


if __name__ == '__main__':
    main(sys.argv[1])
